---
title: "Data and Methods"
output:
  pdf_document:
    latex_engine: xelatex
mainfont: Times New Roman
bibliography: Bibliography.bib
link-citations: yes
csl: journal-of-finance.csl
fontsize: 12pt
geometry: [top=2.5cm, bottom=2.5cm, right=2.5cm, left=3cm]
header-includes:
- \usepackage{setspace}
- \onehalfspacing
---

# Data and Methods

## Sample Selection


The sample for baseline research setting includes US listed firms during the period of 1980-2017. Data for foreign, domestic and institutional shareholdings is retrieved from Thomson Reuters institutional holdings (form 13F) database. To calculate the stock price related control variables, the information asymmetry proxies C2 and VCV and foreign, domestic and institutional ownership measures, I gather stock price information from the Center for Research in Security Prices (CRSP). Accounting related control variables are collected from COMPUSTAT. The 13F data is merged with CRSP by matching the 8-digit CUSIP identifier from 13F to the 8-digit NCUSIP from CRSP. Firm-year estimates of information asymmetry proxies PINBHL (Brown, Hillegeist and Lo, 2004), PINBH (Brown and Hillegeist, 2007), PINEHO (Easley, Hvidkjaer and O’Hara, 2010), PINDY (Duarte and Young, 2009), Adjusted PIN (Duarte and Young, 2009) and firm-day estimates of MIA [@johnson2017simple] are collected from the cited authors’ websites . Information asymmetry measures are merged with the baseline sample by using the CRSP’s Permanent Issue Number (PERMNO) as a linking identifier.

# References

