---
title: "Thesis"
output:
  pdf_document:
    toc: true
    latex_engine: xelatex
  toc-title: "Table of Contents"
mainfont: Times New Roman
bibliography: Bibliography.bib
csl: journal-of-financial-economics.csl
link-citations: yes
fontsize: 12pt
geometry: [top=2.5cm, bottom=2.5cm, right=2.5cm, left=3cm]
header-includes:
- \usepackage{setspace}
- \onehalfspacing
---

\newpage

# 2 Literature review

## 2.1 Information asymmetry and analyst coverage

Earlier literature studies asymmetric information in financial markets by examining the strategic behavior of investors. Kyle (1985) studies the strategic behavior of investors by a market microstructure model in which uninformed trades follow Brownian motion and market makers see only the order imbalance which they fill with matching orders that are crossed at the market-clearing price. Orders are batched and therefore there are no bid and ask prices. The optimal trading behavior for the single informed investor is to exploit his information on trades gradually. In contrast, Glosten and Milgrom (1985) propose a microstructure model in which uninformed orders arrive as a Poisson process and orders are executed individually by market makers. They argue that due to informed investors, there is a positive bid-ask spread even when the market maker is risk-neutral and makes zero profits. 

Several researchers have developed various measures to estimate the magnitude of information asymmetry. Easley et al. (1996) use a market microstructure model inspired by Glosten and Milgrom (1985) in which trade order flows affect the beliefs of market participants. The information of trade order flow is analyzed to estimate the magnitude to which trade order flows convey different information for different securities. As a result, they construct the well-known measure of the probability of informed trading (PIN) of which different researchers have developed various versions (e.g. Brown et al., 2004; Brown and Hillegeist, 2007; Duarte and Young, 2009; Easley et al., 2010). Llorente et al. (2002) develop the C2 measure by examining the relation of daily trading volume and return persistence. They argue that the trades by uninformed investors are likely to result in return reversals, since the expected payoff of a stock is not altered, but the trades by informed investors are likely to result in the continuation of return pattern due to private information that gradually impounds into the market price. Johnson and So (2017) assume that informed investors trade more in options than uninformed investors. Based on the premise, they construct the multimarket information asymmetry (MIA) measure with daily trading volume data of stocks and options. Lof and van Bommel (2018) propose an easily computed measure of volume coefficient variation (VCV). They argue that orders of uninformed (informed) liquidity seekers are uncorrelated (perfectly correlated) and informed orders need to be matched by market makers. From the distribution of total trading volume, they construct functions of the proportion of informed trade and show that the coefficient of variation (the ratio of standard deviation to the mean) of trading volume increases monotonically in the proportion of informed trade.

A great amount of literature finds that equity research analysts produce relevant and valuable information for investors and firms (e.g. Womack, 1996; Barber et al., 2001; Jegadeesh et al., 2004; Loh and Stulz, 2011). Furthermore, as providers of information of the covered firms, analysts are also monitoring these firms (Moyer et al., 1989; Chung and Jo, 1996) and they help to reduce information asymmetry (Bushman and Smith, 2001; Healy and Palepu, 2001). Accordingly, Kelly and Ljungqvist (2012) find in a quasi-experimental research setting that an exogenous decrease in analyst coverage of a firm results in an increase of information asymmetry. Subsequently, many researchers have applied the setting of Kelly and Ljungqvist (2012) to study the effects of exogenous variation in analyst coverage on corporate policies (Derrien and Kecskes, 2013), innovation (He and Tian, 2013) and corporate tax aggressiveness (Allen et al., 2016).

## 2.2 Foreign ownership and information asymmetry

Foreign investors are generally thought to be less informed of local stock markets than local investors among finance practitioners and academics. Domestic investors are found to have better information and support from regulators. For instance, the home bias, the volatility of capital flows and herding among foreign investors are explained to be due to superior information of domestic investors as well as to regulators’ bias against foreign investors (Choe et al., 2005). Although the literature of early 2000s provides some opposite evidence of information asymmetry between domestic and foreign investors (Grinblatt and Keloharju, 2000; Seasholes, 2000), the most recent studies support the traditional view that foreign investors are at an information disadvantage compared to domestic investors (Hau, 2001; Choe et al., 2005; Dvorak, 2005). 

Compared to large literature of describing information advantages of domestic and foreign investors, the relationship of foreign ownership and information asymmetry is less studied. Jiang and Kim (2004) find evidence of inverse relation between foreign ownership and information asymmetry in Japanese markets by focusing on the relation between the level of foreign shareholdings and a measurable consequence of information asymmetry of which they use the timing and magnitude of intertemporal return-earnings associations. Furthermore, they provide evidence that foreign investors tend to avoid stocks with high cross-corporate holdings. However, Choi et al. (2013) report that high foreign ownership is associated with high information asymmetry using a bid-ask spread as a proxy for information asymmetry. In contrast, He et al. (2013) use a well-known measure of the probability of informed trading (PIN) and price non-synchronicity as proxies for information asymmetry when examining the connection between foreign ownership and information asymmetry with a cross-sectional dataset of firms in 40 markets in 2002. They find, as well, that firms with large foreign ownership typically have more informative stock prices (i.e. low information asymmetry) but they rather strongly, given that they limit their conclusion only to a cross-sectional regression results, assume that large foreign ownership causes low information asymmetry. 

I contribute to the existing literature by examining the relationship of foreign ownership and information asymmetry not just with a panel regression but also with a difference-in-differences research setting of brokerage closures (Kelly and Ljungqvist, 2012) which cause an exogenous shock to the analyst coverage of a firm’s stock. Kelly and Ljungvist (2012) and Derrien and Kecskes (2013) argue that an exogenous decrease in analyst coverage causes an increase in information asymmetry of the covered firm. As a result, the research setting of brokerage closures enables me to assess the causal effect between information asymmetry and foreign ownership. Previous studies of information asymmetry and foreign ownership (Jiang and Kim, 2004; Choi et al., 2013; He et al., 2013) do not examine causality profoundly, which makes this thesis a first attempt, to the best of my knowledge, to study the causal effect of information asymmetry on foreign ownership. In addition, I test the general relationship of these two with panel regressions by using various proxies for information asymmetry such as PIN by various researchers (Easley et al., 2010; Brown, Hillegeist and Lo, 2004; Brown and Hillegeist, 2007; Duarte and Young, 2009), MIA (Johnson and So, 2017) and VCV (Lof and van Bommel, 2018).


# 3 Hypotheses

In this thesis, I study the effect of information asymmetry on foreign ownership in US stock markets. In particular, I examine how the foreign ownership of US stocks are affected by an exogenous reduction in analyst coverage using a credible quasi-experiment of brokerage closures (Kelly and Ljungqvist, 2012). Moreover, I test the general relationship of foreign ownership and information asymmetry with alternative proxy measures for information asymmetry in a panel regression setting. Based on these research settings, I construct the following hypotheses:

*H1: Stocks with higher information asymmetry are associated with low foreign ownership*

*H2: An exogenous increase in information asymmetry of stocks results in a decrease of foreign ownership*

*H3: The reduction of foreign ownership due to an exogenous information asymmetry shock is emphasized in stocks with low institutional ownership and analyst coverage*

The first hypothesis is mainly supported by the existing literature. (fix: Jiang and Kim (2004) and He et al. (2013) find an inverse connection between foreign ownership and information asymmetry using the timing and magnitude of intertemporal return-earnings associations in Japanese markets and the probability of informed trading in multiple countries as proxies for information asymmetry, respectively). In contrast, @choi2013foreign provide opposite results with a bid-ask spread in Chinese markets as a corresponding proxy.

Although the existing literature supports the hypothesis of the inverse relation between information asymmetry and foreign ownership, few studies address the causal relationship of these two variables directly as described in the second hypothesis. Based on their overall results, @jiang2004foreign argue that foreign investors are attracted to firms with low information asymmetry in Japanese markets. (FIX: @he2013large interpret similar results of the inverse relation to be due to a view that foreign investors contribute positively to the informativeness of stock prices). However, they point out that the potential reverse causality may drive their results but find it conceptually less likely. They argue that foreign investors could improve corporate governance and disclosure policies of firms of the invested firms. In the spirit of Granger causality test, they run a predictive regression with a one-year lag of dependent variable and find results to be consistent with foreign ownership Granger-causing price informativeness. @batten2015foreign find in Vietnamese markets that foreign investors prefer firms of which characteristics are associated with low information asymmetry, such as large size, low leverage and high book-to-market ratio to overcome the information disadvantage compared to domestic investors. Furthermore, their finding is in line with previous studies of home bias that find foreign investors preferring firms with comfortable characteristics like large size or low leverage [@kang1997there; @dahlquist2001direct].

The existing literature finds that institutional investors can act as active monitors of management by directly intervening in a firm’s operations [@shleifer1986large; @gillan2003corporate; @ferreira2008colors]. As a result of monitoring, information asymmetry of a stock is reduced. Accordingly, less uninformed investors like foreign investors consider institutional ownership as a convincing signal that information asymmetry risk of a given stock is mitigated [@luong2015]. Similarly, @lof2018asymmetric argue that an exogenous decrease of analyst coverage is a greater shock for a firm that initially has a low analyst coverage. Hence, the third hypothesis is largely supported by existing literature.


# 4 Data

## 4.1 Sample Selection


Since the country information of the institutions in the 13F data is only from June 1997, I limit the sample to include US listed firms (NYSE, AMEX and Nasdaq) during the period of 1997-2017. Data for foreign, domestic and institutional shareholdings is retrieved from Thomson Reuters institutional holdings (form 13F) database. To calculate the stock price related control variables, the information asymmetry proxies *BID_ASK_SPREAD*, *VCV* and foreign, domestic and institutional ownership measures, I gather stock price information from the Center for Research in Security Prices (CRSP). Accounting related control variables are collected from COMPUSTAT. The 13F data is merged with CRSP by matching the 8-digit CUSIP identifier from 13F to the 8-digit NCUSIP from CRSP. I use CRSP-COMPUSTAT Merged Database (CCM) to merge CRSP and COMPUSTAT datasets. Firm-year estimates of information asymmetry proxies *PIN~BHL~* [@brown2004conference], *PIN~BH~* [@brown2007disclosure], *PIN~EHO~* [@easley2010factoring], *PIN~DY~* [@duarte2009pin], *Adjusted PIN* and firm-day estimates of *MIA* [@johnson2017simple] are collected from the cited authors’ websites [^1]. Information asymmetry measures are merged with the baseline sample by using the CRSP’s Permanent Issue Number (PERMNO) as a linking identifier.

[^1]:Firm-year observations of PINBH, PINBHL, PINEHO and PINDY are made available
by Søren Hvidkjær (https://sites.google.com/site/hvidkjaer/data), Stephen Brown (http://scholar.rhsmith.umd.edu/sbrown/pin-data) and Jefferson Duarte (http://www.owlnet.rice.edu/~jd10/),
respectively. Daily firm-level observations of MIA are made available by Travis Johnson (http://travislakejohnson.com/data.html).


## 4.2 Constructing the variables

I extract foreign ownership data from Thomson Reuters institutional holdings (form 13F) s34 master file. I define two variables *FOREIGN_HOLDINGS* and *FOREIGN_BREADTH* of which the former is defined as an annual average of the shares of a firm held by foreign institution at the end of each quarter divided by the firm’s total shares outstanding at the end of each quarter. The latter is defined as an annual average of the number of distinct foreign institutions holding shares in the firm at the end of each quarter divided the total number of institutions in the 13F database at the end of each quarter [@chen2002breadth; @lof2018asymmetric]. I retrieve shares outstanding data from CRSP monthly file. I also construct the variables for total institutional ownership *INSTITUTIONAL_HOLDINGS* and *INSTITUTIONAL_BREADTH* in a similar manner. In comparison of the firm-year level dataset in the baseline research setting, I construct the variables for the quasi-experimental research sample, I construct the variables similarly but at the firm-quarter level.  

I obtain data for information asymmetry measures of annual firm-level PIN and daily firm-level MIA observations from the cited researchers’ publicly available websites. I construct the firm-year observations of MIA by calculating the annual average of daily observations for each firm. Data for proxy measure VCV is retrieved from CRSP daily stock file. Following Lof and van Bommel (2018), I construct the annual firm-level observations of VCV by computing the fraction of the annual standard deviation of daily trading volumes and the annual average of daily trading volumes. I require firms to have at least 200 days with a positive trading volume in a year. Similarly, I calculate the *VCV* using three different measures of trading volume: volume in US dollars, volume market shares and turnover.

I gather control variables data from COMPUSTAT quarter fundamentals and CRSP monthly stock files. I compute *LOG_MARKET_CAP* by multiplying market price of each stock by the shares outstanding at the end of each quarter, converting it to an annual average and taking the logarithm of this measure. *BM_RATIO* is an annual average of the stock's book value of equity divided by the market value at the end of each quarter. *LEVERAGE* is an annual average of the stock's total debt divided by total assets at the end of each quarter. *ROA* is an annual average of the stock's net income divided by total assets at the end of each quarter. I use SIC codes from CRSP to capture the corresponding industry for each stock.

## 4.3 The quasi-natural experiment

For the quasi-natural experiment, I limit the time period of the original sample to 1997-2011 to cover the time period of 22 distinct brokerage closures from June 2000 until January 2008 listed in Appendix A of Kelly and Ljungqvist (2012) plus three years of pre- and post-treatment periods. I identify stocks that lose an analyst covering the firm because of the brokerage closures which provide a source of exogenous variation for the analyst coverage. The list is matched with an analyst coverage data retrieved from the Institutional Brokers’ Estimate System (IBES) detail file. 
To construct the sample of treated firms, I filter out firms that are not covered by analysts employed in the brokerage houses listed in Appendix A of @kelly2012testing. Following @derrien2013real, I require for the treated firms to be covered by an analyst at least one year before the disappearance dates to filter out firms that are not actively covered by the analysts. Furthermore, following @kelly2012testing and @derrien2013real, I only retain firms for which the analyst has not “stopped” his estimate before the corresponding broker disappearance date to eliminate the potential endogeneity problem. For instance, if an analyst terminates the coverage of firms unrelated to the brokerage closure before the disappearance date (e.g. anticipating changes in corporate policies), the decision is endogenous. I collect the data for stopped estimates from IBES stop file. Since the brokerage closure dates listed by @kelly2012testing and corresponding disappearance dates do not coincide completely, I follow @derrien2013real, @he2013dark and @lof2018asymmetric to construct a three-month gap before and after the event date. As a result, I estimate the dependent variables and explanatory variables for each stock in a given quarter by subtracting (adding) three months from the event date and finding the previous (next) available quarter value for before and after measures, respectively. Moreover, I define the variable *ANALYST_COVERAGE* as the number of distinct analysts covering a firm in a given quarter.





# 5 Methodology

To empirically examine the first hypothesis of the thesis, I use a panel regression model for the baseline sample. A difference-in-differences regression model is employed to test the second and third hypotheses. 

## 5.1 The panel regression model

I test the relation of foreign ownership and information asymmetry by using the following panel regression model of firm-year observations:

\begin{equation}
\scriptsize
\begin{aligned}
FOREIGN\_OWNERSHIP_{i,t} &= \beta_0 + \beta_{1}INFORMATION\_ASYMMETRY_{i,t} + \beta_{2}LOG\_MARKET\_CAP_{i,t}\\
&+ \beta_{3}BM\_RATIO_{i,t} + \beta_{4}LEVERAGE_{i,t} + \beta_{5}ROA_{i,t}\\ &+ \sum_{t=1}^T YEAR_t + \sum_{n=1}^N INDUSTRY_n + \epsilon_{i,t}
\end{aligned}
\end{equation}

Foreign_ownership is measured by either of the two variables: Foreign_holdings (defined as shares of a firm held by foreign institution, as a percentage of the firm’s shares outstanding at the end of each year) and Foreign_breadth (defined as the number of distinct foreign institutions holding shares in the firm, as a percentage of the total number of institutions in the 13F database at the end of each year – Chen et al., 2002; Lof and van Bommel, 2018). Information_asymmetry is, similarly, measured by one of the various proxy variables: PIN¬BHL, PINBH, PINEHO, PINDY, Adjusted_PIN, MIA, C2, and VCV. Due to each combination of list variables Foreign_ownership and Information_asymmetry, I have results from 14 different regressions. LogMktCap is the logarithm of market capitalization at the end of each year. BM_ratio is the book value of equity divided by the market value at the end of each year. Leverage is the total debt divided by total assets at the end of each year. I also include year and industry fixed effects.

## 5.2 The difference-in-differences regression model

I examine the effect of an exogenous increase in information asymmetry on foreign ownership of a firm by using the following difference-in-differences regression of firm-quarter observations:

\begin{equation}
\scriptsize
\begin{aligned}
FOREIGN\_OWNERSHIP_{i,t} &= \beta_0 + \beta_{1}TREATED_{i} + \beta_{2}AFTER_{t} + \beta_{3}AFTER\times TREATED_{i,t}\\ &+ \beta_{4}LOG\_MARKET\_CAP_{i,t} + \beta_{5}BM\_RATIO_{i,t} + \beta_{6}LEVERAGE_{i,t}\\ &+ \beta_{7}ROA_{i,t} + \sum_{t=1}^T YEAR_t + \sum_{n=1}^N INDUSTRY_n + \epsilon_{i,t}
\end{aligned}
\end{equation}


Similarly, as in the panel regression model, Foreign_ownership is a list of variables Foreign_holdings and Foreign_breadth. Treated is a dummy variable indicating observations of firms that are in the treatment group. Post is defined as a dummy variable for observations that occur after each brokerage closure event. The variable of interest is the interaction term of these two variables or the difference-in-differences estimator which captures the effect of treatment. Moreover, I include year and industry fixed effects.

# References
